### ISSUE TITLE
Macro implementation

### ISSUE THREAD

**Issue by antoine-levitt** [tpapp/SymmetricProducts.jl#1]
`B = @sym A'*A` would be pretty cool.

**Comment by tpapp** [comment]
I am reluctant to use a macro unless I need a source transformation.

Here it would involve verifying the redundancy, but IMO not introducing it in the first place is better.

**Comment by antoine-levitt** [comment]
Agreed that it's better to not have redundancy, but still `A'A` reads nicer than `symprod(A)`. Especially if other types of operations are allowed, remembering the API might be annoying.

**Comment by tpapp** [comment]
I will think about this, but for now this is beyond the goals of this package.

**Comment by tpapp** [comment]
I think the syntax of #3 takes care of this.
